# Generated by Django 5.1.2 on 2024-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_donor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='profile',
            field=models.FileField(default=1, upload_to='document/'),
            preserve_default=False,
        ),
    ]
